---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "🦄 Developer Experience 🔥"
subtitle: "Red Hat Open Innovation Labs"
# logo: "https://avatars1.githubusercontent.com/u/19174470?s=200&v=4"
logo: "https://www.redhat.com/cms/managed-files/RHOIL_LogoBadge_RGB_Default.svg"
# icon: "fas fa-skull-crossbones" Optional icon
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>'  # set false if you want to hide it.

# Optional message
# message:
#   # url: https://....
#   style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#   title: "Demo !" 
#   content: "This is a dummy homepage demo. Find more information on github.com/bastienwirtz/homer"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Ubiquitous Journey"
    icon: "fab fa-github"
    url: "https://github.com/rht-labs/ubiquitous-journey"
    target: '_blank' # optionnal html a tag target attribute
  - name: "Open Management Portal"
    icon: "fab fa-github"
    url: "https://github.com/rht-labs/open-management-portal"
  - name: "Helm Charts"
    icon: "fab fa-github"
    url: "https://github.com/rht-labs/helm-charts"
  - name: "DO500 "
    icon: "fab fa-github"
    url: "https://github.com/rht-labs/enablement-docs"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).

      # - name: ""
      #   logo: ""
      #   subtitle: ""
      #   tag: ""
      #   url: ""
      #   target: '_blank'

services:
  - name: "Automation"
    icon: "fas fa-code-branch"
    items:
      - name: "Jenkins"
        logo: "assets/tools/jenkins.png"
        subtitle: "Continuous integration server"
        tag: "CI"
        url: "https://jenkins-labs-ci-cd.apps.s43.core.rht-labs.com"
        target: '_blank' # optionnal html a tag target attribute
      - name: "ArgoCD"
        logo: "https://argoproj.github.io/argo-cd/assets/logo.png"
        subtitle: "Git driven Operations"
        tag: "CI, GitOps"
        url: "https://labs-argocd-labs-ci-cd.apps.s43.core.rht-labs.com"
        target: '_blank'
      - name: "CodeReady Workspaces"
        logo: "https://github.com/redhat-developer/codeready-workspaces/raw/master/product/branding/CodeReady.png"
        subtitle: "Cloud hosted dev stack"
        tag: "dev"
        url: "https://codeready-crw.apps.s43.core.rht-labs.com/dashboard/"
        target: '_blank'
      - name: "Nexus"
        logo: "https://user-images.githubusercontent.com/7955995/29498304-ee71d418-85c6-11e7-9f95-e87a4439ed3c.png"
        subtitle: "Software artifact repository"
        url: "https://nexus-labs-ci-cd.apps.s43.core.rht-labs.com"
        target: '_blank'
      - name: "SonarQube"
        logo: "https://www.sonarqube.org/images/downloads/picto.svg"
        subtitle: "Software quality tooling"
        url: "https://sonarqube-labs-ci-cd.apps.s43.core.rht-labs.com"
        target: '_blank'
      - name: "Zalenium"
        logo: "https://gitlab.com/okj8/zalenium/-/avatar"
        subtitle: "Browser testing tools"
        url: "https://zalenium-labs-ci-cd.apps.s43.core.rht-labs.com"
        target: '_blank'
  - name: "Monitoring"
    icon: "fas fa-heartbeat"
    items:
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "Metric analytics & dashboards"
        url: "https://grafana.com/"
      - name: "Prometheus"
        logo: "https://d15shllkswkct0.cloudfront.net/wp-content/blogs.dir/1/files/2017/11/prometheus_logo.png"
        subtitle: "Collect Mertics"
        tag: "metrics"
        url: "https://www.elastic.co/products/kibana"
  - name: "Project Management"
    icon: "fas fa-tasks"
    items:
      - name: "Wekan"
        logo: "https://avatars0.githubusercontent.com/u/11725037?s=200&v=4"
        subtitle: "Wekan Tasks"
        tag: "Wekan, kanban"
        url: "https://wekan-labs-ci-cd.apps.s43.core.rht-labs.com/"
      - name: "Mattermost"
        logo: "https://images.g2crowd.com/uploads/product/image/large_detail/large_detail_0b2e8ea823612a322cf779c35039d756/mattermost.png"
        subtitle: "Cluster hosted Chat app"
        tag: "chat"
        url: "https://mattermost-team-edition-labs-ci-cd.apps.s43.core.rht-labs.com"
        target: '_blank' # optionnal html a tag target attribute
